[package]
name = "simplevidview"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ffmpeg-next = "8.0.0"
rfd = "0.15.4"
sdl2 = "0.38.0"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_LibraryLoader"] }

[build-dependencies]
winres = "0.1.12"
